/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eltho
 */
public class Battle extends javax.swing.JFrame {

    /**
     * Creates new form battle
     */
    public Battle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelMPJogador = new javax.swing.JLabel();
        labelVidaJogador1 = new javax.swing.JLabel();
        labelVidaInimigo = new javax.swing.JLabel();
        labelMPInimigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaJogador = new javax.swing.JTextArea();
        btnSPAttack = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        btnAttack = new javax.swing.JButton();
        btnDefense = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Jogador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Inimigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 82, -1));

        labelMPJogador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMPJogador.setText("Mana: 0");
        getContentPane().add(labelMPJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 160, -1));

        labelVidaJogador1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVidaJogador1.setText("Vida: 0");
        getContentPane().add(labelVidaJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, -1));

        labelVidaInimigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVidaInimigo.setText("Vida: 0");
        getContentPane().add(labelVidaInimigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 160, -1));

        labelMPInimigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMPInimigo.setText("Mana: 0");
        getContentPane().add(labelMPInimigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 160, -1));

        txtAreaJogador.setColumns(20);
        txtAreaJogador.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtAreaJogador.setRows(5);
        txtAreaJogador.setText("O que Charmeleon deve fazer ?\n");
        jScrollPane1.setViewportView(txtAreaJogador);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 480, 805, 234));

        btnSPAttack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSPAttack.setText("Ataque SP");
        getContentPane().add(btnSPAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 480, 152, 104));

        btnRun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRun.setText("Fugir");
        getContentPane().add(btnRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 602, 152, 104));

        btnAttack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAttack.setText("Ataque");
        btnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttackActionPerformed(evt);
            }
        });
        getContentPane().add(btnAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 480, 152, 104));

        btnDefense.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDefense.setText("Defender");
        getContentPane().add(btnDefense, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 602, 152, 104));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charmeleon.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 174, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noivern.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 267, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/field_1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttackActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttack;
    private javax.swing.JButton btnDefense;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnSPAttack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMPInimigo;
    private javax.swing.JLabel labelMPJogador;
    private javax.swing.JLabel labelVidaInimigo;
    private javax.swing.JLabel labelVidaJogador1;
    private javax.swing.JTextArea txtAreaJogador;
    // End of variables declaration//GEN-END:variables
}
